### ISSUE TITLE
Suggestion?

### ISSUE THREAD

**Issue by EvilG-MC** [Tomato6966/lavalink-client#13]
This may be strange, but there is a possibility that the `LavalinkManager class` has a method either `LavalinkManager#search` or `LavalinkManager#searchTrack`, exclusively to search for songs, without having to create/get the player, just get the song full result list.

I really hope I can explain myself...

~_I can't assign labels or anything, So I used the title haha_~

**Comment by Tomato6966** [comment]
As already explained in other issues:
I dont allow search from manager, because if u search from a different node, than your player is. And you play from that searchresult, the player will fail.
Therefore you can use node.search and node.lavaSearch.

To access a node without creating the player do
manager.nodeManager.nodes.get("id")

**Comment by EvilG-MC** [comment]
I see, in my case it was for an autocomplete and I need only the search results, I'll try with that, thanks for answering!

**Comment by Tomato6966** [comment]
In my autocomplete, i create the player.

You dont need to connect it before you search, so it really is zero delay.. Anyways
